## Numpy 

In [ ]:
Numpy >> Numerical Python

In [4]:
import numpy as np
import pandas as pd

#### Application

In [ ]:
1. Linear Algebra
2. Statistics
3. Trigonometry
4. Matrix Operations
5. IMage Processing
6. Logarithmic 


### Properties

In [ ]:
1. It is a collection homogeneous datatypes
2. Numpy is faster than List
3. Numpy is written in C and C++ Language (Partially in Python)
4. C Language is Faster than Python

numpy.ndarray >> n-Dimensional Array

int >> float >> complex >> str

In [2]:
list1 = [1,3,5,7.8,3.14, 'python', 'data science']

## Numpy Functions

In [ ]:
1. np.array()
2. array.ndim
3. array.shape
4. array.tolist() >> N-Dimensioanl Numpy array tolist

### 1. np.array

In [21]:
array1 = np.array([3,4,6,7,8])
array1

array([3, 4, 6, 7, 8])

In [23]:
array1 = np.array((3,4,6,7,8))
array1

array([3, 4, 6, 7, 8])

In [28]:
list1 = [3,4,5,6,7,8]
array1 = np.array(list1)
array1

array([3, 4, 5, 6, 7, 8])

In [30]:
array1 = np.array(100)
array1

array(100)

In [31]:
set1 = {3,4,5,6,7,8}
array1 = np.array(list(set1))
array1

array([3, 4, 5, 6, 7, 8])

In [15]:
array1 = np.array([2,3,5,6,7,8])
array1

array([2, 3, 5, 6, 7, 8])

In [16]:
type(array1)

numpy.ndarray

In [9]:
print(array1)

[2 3 5 6 7 8]


In [11]:
array1 = np.array([2,3,5,6.9,7,8])
array1

array([2. , 3. , 5. , 6.9, 7. , 8. ])

In [19]:
array1 = np.array([2,3,5,6.9,7,8,4+5j])
array1

array([2. +0.j, 3. +0.j, 5. +0.j, 6.9+0.j, 7. +0.j, 8. +0.j, 4. +5.j])

### Type Casting in Numpy Array

In [ ]:
int >> float
int >> complex
int >> str/object

In [33]:
array1 = np.array([3,4,5,6,7])
array1

array([3, 4, 5, 6, 7])

In [35]:
array1 = np.array([3,4,5,6,7],dtype = int)
array1

array([3, 4, 5, 6, 7])

In [37]:
array1 = np.array([3,4,5,6,7],dtype = 'int')
array1

array([3, 4, 5, 6, 7])

In [39]:
array1 = np.array([3,4,5,6,7],dtype = 'i')
array1

array([3, 4, 5, 6, 7], dtype=int32)

In [41]:
array1 = np.array([3,4,5,6,7],dtype = float)
array1

array([3., 4., 5., 6., 7.])

In [43]:
array1 = np.array([3,4,5,6,7],dtype = 'float')
array1

array([3., 4., 5., 6., 7.])

In [45]:
array1 = np.array([3,4,5,6,7],dtype = 'f')
array1

array([3., 4., 5., 6., 7.], dtype=float32)

In [47]:
array1 = np.array([3,4,5,6,7],dtype = complex)
array1

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [51]:
array1 = np.array([3,4,5,6,7],dtype = 'complex')
array1

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [53]:
array1 = np.array([3,4,5,6,7],dtype = str)
array1

array(['3', '4', '5', '6', '7'], dtype='<U1')

In [55]:
array1 = np.array([3,4,5,6,7],dtype = 'str')
array1

array(['3', '4', '5', '6', '7'], dtype='<U1')

In [56]:
array1 = np.array([3,4,5,6,7],dtype = object)
array1

array([3, 4, 5, 6, 7], dtype=object)

In [ ]:
str >> object

#### Float to other Datatypes

In [58]:
array1 = np.array([3,4,5.45,6.12,6,7])
array1

array([3.  , 4.  , 5.45, 6.12, 6.  , 7.  ])

In [60]:
array1 = np.array([3,4,5.45,6.12,6,7],dtype = 'float')
array1

array([3.  , 4.  , 5.45, 6.12, 6.  , 7.  ])

In [62]:
array1 = np.array([3,4,5.45,6.12,6,7],dtype = float)
array1

array([3.  , 4.  , 5.45, 6.12, 6.  , 7.  ])

In [70]:
array1 = np.array([3,4,5.45,6.12,6,7],dtype = int)
array1

array([3, 4, 5, 6, 6, 7])

In [72]:
int(5.78)

5

In [74]:
array1 = np.array([3,4,5.45,6.90,8,7],dtype = int)
array1

array([3, 4, 5, 6, 8, 7])

In [69]:
array1 = np.array([3,4,5.45,6.12,6,7],dtype = complex)
array1

array([3.  +0.j, 4.  +0.j, 5.45+0.j, 6.12+0.j, 6.  +0.j, 7.  +0.j])

In [68]:
array1 = np.array([3,4,5.45,6.12,6,7],dtype = str)
array1

array(['3', '4', '5.45', '6.12', '6', '7'], dtype='<U4')

### Complex to other datatypes

In [ ]:
can't convert complex to int

In [76]:
array1 = np.array([4+6j, 10,20,30,40])
array1

array([ 4.+6.j, 10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j])

In [78]:
array1 = np.array([4+6j, 10,20,30,40],dtype = int)
array1

TypeError: can't convert complex to int

In [80]:
array1 = np.array([4+6j, 10,20,30,40],dtype = float)
array1

TypeError: can't convert complex to float

In [82]:
int(3+4j)

TypeError: can't convert complex to int

### Numeric Operation

In [84]:
array2 = np.array([3,4,5,6,7])
array2

array([3, 4, 5, 6, 7])

In [87]:
list1 = [3,4,5,6,7]
cube_list = [i**3 for i in list1]
cube_list

[27, 64, 125, 216, 343]

In [89]:
list1 = [3,4,5,6,7]
result = [i*10 for i in list1]
result

[30, 40, 50, 60, 70]

In [91]:
array2 = np.array([3,4,5,6,7])
array2 * 10

array([30, 40, 50, 60, 70])

In [93]:
array2 = np.array([3,4,5,6,7])
array2 + 100

array([103, 104, 105, 106, 107])

In [95]:
array2 = np.array([3,4,5,6,7])
array2 ** 2

array([ 9, 16, 25, 36, 49], dtype=int32)

In [97]:
array2 = np.array([3,4,5,6,7])
array2 ** 3

array([ 27,  64, 125, 216, 343], dtype=int32)

In [99]:
array2 = np.array([3,4,5,6,7])
array2/2

array([1.5, 2. , 2.5, 3. , 3.5])

In [100]:
array2 = np.array([3,4,5,6,7])
array2//2

array([1, 2, 2, 3, 3], dtype=int32)

In [102]:
array2 = np.array([3,4,5,6,7])
array2 % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [104]:
array2 = np.array([3,4,5,6,7])
array2 % 3

array([0, 1, 2, 0, 1], dtype=int32)

In [106]:
array2 = np.array([3,4,5,6,7])
array2 - 5

array([-2, -1,  0,  1,  2])

In [108]:
list1 = [3,4,5,6,7]
array1 = np.array(list1)
array1 ** 3


array([ 27,  64, 125, 216, 343], dtype=int32)

In [112]:
list1 = [3,4,5,6,7]
cubes = np.array(list1) ** 3
cubes.tolist()

[27, 64, 125, 216, 343]

In [115]:
list1 = [3,4,5,6,7]
cubes = np.array(list1) ** 3
list(cubes)

[27, 64, 125, 216, 343]

In [ ]:
list1 = [3,4,5,6,7]
cubes = np.array(list1) ** 3
list(cubes)

In [118]:
list1 = [3,4,5,6,7]
cubes = (np.array(list1) ** 3).tolist()
cubes

[27, 64, 125, 216, 343]

### Dimensions in Numpy Array

##### 1. Zero-Dimensional Array

In [120]:
array0 = np.array(50)
array0

array(50)

In [123]:
array0 = np.array(50)
print("Number of Dimensions are :",array0.ndim)

Number of Dimensions are : 0


#### 2. One-Dimensional Array

In [ ]:
It is collection of multiple 0-D arrays

In [126]:
array1 = np.array([4,5,6,7])
print("Array is :",array1)
print("Number of Dimensions are :",array1.ndim)

Array is : [4 5 6 7]
Number of Dimensions are : 1


In [128]:
array1 = np.array([4,5,6,7,102,40,50,90])
print("Array is :",array1)
print("Number of Dimensions are :",array1.ndim)

Array is : [  4   5   6   7 102  40  50  90]
Number of Dimensions are : 1


#### 3. Two Dimensional Array

In [ ]:
It is collection of multiple 1-D arrays

In [137]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90]])
print("Array is :\n",array2)
print("Number of Dimensions are :",array2.ndim)
len(array2)

Array is :
 [[  4   5   6]
 [  7 102  40]
 [ 10  50  90]]
Number of Dimensions are : 2


3

In [138]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90,100]])
print("Array is :\n",array2)
print("Number of Dimensions are :",array2.ndim)
len(array2)

Array is :
 [list([4, 5, 6]) list([7, 102, 40]) list([10, 50, 90, 100])]
Number of Dimensions are : 1


<ipython-input-138-36dbbf980849>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array2 = np.array([[4,5,6],[7,102,40],[10,50,90,100]])


3

In [139]:
list1 = [[4,5,6],[7,102,40],[10,50,90]]
len(list1)
list1

[[4, 5, 6], [7, 102, 40], [10, 50, 90]]

In [ ]:
[4,5,6],
[7,4,5],
[3,6,7,9]

In [142]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90]])
array2

array([[  4,   5,   6],
       [  7, 102,  40],
       [ 10,  50,  90]])

In [144]:
array2.ndim

2

In [146]:
array2.shape

(3, 3)

In [149]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90],[1,2,3]])
array2

array([[  4,   5,   6],
       [  7, 102,  40],
       [ 10,  50,  90],
       [  1,   2,   3]])

In [150]:
array2.ndim

2

In [152]:
array2.shape

(4, 3)

In [155]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90],[1,2,3]])
print("Number of Rows :",array2.shape[0])
print("Number of Columns :",array2.shape[1])

Number of Rows : 4
Number of Columns : 3


In [158]:
array2 = np.array([[4,5,6],[7,102,40],[10,50,90],[1,2,3]])
rows_count = array2.shape[0]
col_count = array2.shape[1]
print("Number of Rows :",rows_count)
print("Number of Columns :",col_count)

Number of Rows : 4
Number of Columns : 3


### 4. Three Dimensional Array

In [160]:
array3 = np.array([[[4,5,6],[7,102,40],[10,50,90],[1,2,3]]])
len(array3)

1

In [163]:
array3 = np.array([[[4,5,6],[7,102,40],[10,50,90],[1,2,3]]])
array3

array([[[  4,   5,   6],
        [  7, 102,  40],
        [ 10,  50,  90],
        [  1,   2,   3]]])

In [166]:
array3 = np.array([[[4,5,6],[7,102,40],[10,50,90]],[[40,50,60],[70,102,40],[100,500,900]]])
array3

array([[[  4,   5,   6],
        [  7, 102,  40],
        [ 10,  50,  90]],

       [[ 40,  50,  60],
        [ 70, 102,  40],
        [100, 500, 900]]])

In [171]:
array3 = np.array([[[4,5,6],[7,102,40],[10,50,90]],[[40,50,60],[70,102,40],[100,500,900]]])
array3.shape

(2, 3, 3)

In [176]:
array3 = np.array([[[4,5],[7,40],[10,90]],[[40,60],[70,40],[1,500]]])
array3

array([[[  4,   5],
        [  7,  40],
        [ 10,  90]],

       [[ 40,  60],
        [ 70,  40],
        [  1, 500]]])

In [178]:
array3 = np.array([[[4,5],[7,40],[10,90]],[[40,60],[70,40],[1,500]]])
array3.shape

(2, 3, 2)

In [180]:
array3 = np.array([[[4,5],[7,40],[10,90]],[[40,60],[70,40],[1,500]],[[40,60],[70,40],[1,500]]])
array3

array([[[  4,   5],
        [  7,  40],
        [ 10,  90]],

       [[ 40,  60],
        [ 70,  40],
        [  1, 500]],

       [[ 40,  60],
        [ 70,  40],
        [  1, 500]]])

In [181]:
array3 = np.array([[[4,5],[7,40],[10,90]],[[40,60],[70,40],[1,500]],[[40,60],[70,40],[1,500]]])
array3.shape

(3, 3, 2)

In [ ]:
3,3,2

### Access items using indexing and slicing

In [183]:
array1 = np.array([4,5,6,7])
array1

array([4, 5, 6, 7])

In [184]:
array1[0]

4

In [186]:
array1[2]

6

In [188]:
array1[-1]

7

In [189]:
array1[-3]

5

In [192]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2

array([[2, 3, 4, 8],
       [1, 6, 7, 8]])

In [194]:
array2.shape

(2, 4)

In [197]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[0][2]

4

In [199]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[1][1]

6

In [201]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[0,2] # array2[0][2]

4

In [202]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[0,2] # array2[0][2]

4

In [205]:
list1 =[ [4,5,6]]
list1[0][1]

5

In [208]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[-1] 

array([1, 6, 7, 8])

In [211]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[-1,-3]

6

In [213]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[1,1] 

6

In [216]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[1,-3] 

6

In [218]:
array2 = np.array([[2,3,4,8],[1,6,7,8]])
array2[-1,1] 

6

In [220]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2

array([[ 2,  3,  4,  8],
       [ 1,  6,  7,  8],
       [10, 20, 30, 54]])

In [224]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[0:2]

array([[2, 3, 4, 8],
       [1, 6, 7, 8]])

In [226]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[1,2]

7

In [228]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[:,2]

array([ 4,  7, 30])

In [230]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[:,:]

array([[ 2,  3,  4,  8],
       [ 1,  6,  7,  8],
       [10, 20, 30, 54]])

In [232]:
array1 = np.array([3,4,5,6,67,7,8,9,10])
array1[3:6] # 3,4,5

array([ 6, 67,  7])

In [234]:
array1 = np.array([3,4,5,6,67,7,8,9,10])
array1[:3] # 0,1,2

array([3, 4, 5])

In [235]:
array1 = np.array([3,4,5,6,67,7,8,9,10])
array1[-4:] # -4,-3,-2,-1

array([ 7,  8,  9, 10])

In [237]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2

array([[ 2,  3,  4,  8],
       [ 1,  6,  7,  8],
       [10, 20, 30, 54]])

In [240]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[1:,:]

array([[ 1,  6,  7,  8],
       [10, 20, 30, 54]])

In [242]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[1:,2:]

array([[ 7,  8],
       [30, 54]])

In [244]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2[:2,2:] # 0 and 1st row

array([[4, 8],
       [7, 8]])

In [268]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2

array([[ 2,  3,  4,  8],
       [ 1,  6,  7,  8],
       [10, 20, 30, 54]])

In [269]:
array2 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
array2.tolist()

[[2, 3, 4, 8], [1, 6, 7, 8], [10, 20, 30, 54]]

In [250]:
array2[:2,-3:-1] # 0 and 1st row

array([[3, 4],
       [6, 7]])

In [253]:
array2 = np.array([[[2,3,4,8],[1,6,7,8],[1,2,3,4]],[[20,30,40,80],[10,60,70,80],[10,20,30,54]]])
array2

array([[[ 2,  3,  4,  8],
        [ 1,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[20, 30, 40, 80],
        [10, 60, 70, 80],
        [10, 20, 30, 54]]])

In [257]:
array2[1,0,1]

30

In [259]:
array2[:,0,1]

array([ 3, 30])

In [261]:
array2[:,:,:]

array([[[ 2,  3,  4,  8],
        [ 1,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[20, 30, 40, 80],
        [10, 60, 70, 80],
        [10, 20, 30, 54]]])

In [264]:
array2[:,:,2:]

array([[[ 4,  8],
        [ 7,  8],
        [ 3,  4]],

       [[40, 80],
        [70, 80],
        [30, 54]]])

In [265]:
array2[:,:,:-2]

array([[[ 2,  3],
        [ 1,  6],
        [ 1,  2]],

       [[20, 30],
        [10, 60],
        [10, 20]]])

In [270]:
array2 = np.array([[[2,3,4,8],[1,6,7,8],[1,2,3,4]],[[20,30,40,80],[10,60,70,80],[10,20,30,54]]])
print(array2.tolist())

[[[2, 3, 4, 8], [1, 6, 7, 8], [1, 2, 3, 4]], [[20, 30, 40, 80], [10, 60, 70, 80], [10, 20, 30, 54]]]


In [272]:
array1 = np.array([3,4,6,7,8])
array1.shape

(5,)

In [273]:
array1 = np.array(100)
array1.shape

()