### Numpy - Linear Algebra

In [ ]:
1. np.linalg.solve()
2. np.linalg.inv()
3. np.polynomial.Polynomial():
    poly.roots()
4. np.linalg.eig()
5. np.linalg.eigvals()

In [ ]:
2x + 3y = 10
3x + 9y = 20
x = ?
y = ?

In [ ]:
2x + 3y = 10
3x + 9y = 20
x = 3.3
y = 1.1

In [2]:
import numpy as np

In [5]:
array_A = np.array([[2,3],[3,9]])
array_B = np.array([10,20])
print("Array A is :\n",array_A)
print("Array B is :\n",array_B)

Array A is :
 [[2 3]
 [3 9]]
Array B is :
 [10 20]


In [8]:
np.linalg.solve(array_A,array_B)

array([3.33333333, 1.11111111])

In [ ]:
2x + 3y + 5z = 100
3x + 9y + 4z = 140
5x + 3y + 7z = 120

x = ?
y = ?
z = ?

In [12]:
array_A = np.array([[2,3,5],[3,9,4],[5,3,7]])
array_B = np.array([100,140,120])
print("Array A is :\n",array_A)
print("Array B is :\n",array_B)
np.linalg.solve(array_A,array_B)

Array A is :
 [[2 3 5]
 [3 9 4]
 [5 3 7]]
Array B is :
 [100 140 120]


array([-3.7037037 ,  9.87654321, 15.55555556])

### Inverse of an array

In [14]:
array_A = np.array([[2,3],[3,9]])

np.linalg.inv(array_A)

array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [16]:
array_A = np.array([[2,3],[4,5]])

np.linalg.inv(array_A)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [19]:
array_A = np.array([[12,30],[40,50]])

np.linalg.inv(array_A)

array([[-0.08333333,  0.05      ],
       [ 0.06666667, -0.02      ]])

In [21]:
array_A = np.array([[2,3,5],[3,9,4],[5,3,7]])
np.linalg.inv(array_A)

array([[-0.62962963,  0.07407407,  0.40740741],
       [ 0.01234568,  0.13580247, -0.08641975],
       [ 0.44444444, -0.11111111, -0.11111111]])

## Roots

In [ ]:
x2 -5x + 6 = 0
a = 1
b = -5
c = 6

In [25]:

eq = np.polynomial.Polynomial([6,-5,1])
eq.roots()

array([2., 3.])

In [27]:
eq = np.polynomial.Polynomial([6,-5,1])
print(eq)
eq.roots()

6.0 - 5.0 x**1 + 1.0 x**2


array([2., 3.])

In [29]:
eq = np.polynomial.Polynomial([4,5,1])
print(eq)
eq.roots()

4.0 + 5.0 x**1 + 1.0 x**2


array([-4., -1.])

In [31]:
eq = np.polynomial.Polynomial([4,5,2])
print(eq)
eq.roots()

4.0 + 5.0 x**1 + 2.0 x**2


array([-1.25-0.66143783j, -1.25+0.66143783j])

In [34]:
from numpy.polynomial import Polynomial

poly = Polynomial([3,4,2])
poly.roots()

array([-1.-0.70710678j, -1.+0.70710678j])

In [36]:
from numpy.polynomial import Polynomial

poly = Polynomial([3,4,2,1])
poly

Polynomial([3., 4., 2., 1.], domain=[-1,  1], window=[-1,  1])

In [38]:
poly.roots()

array([-1. +0.j       , -0.5-1.6583124j, -0.5+1.6583124j])

### Eigen Values 

In [42]:
array1 = np.random.randint(1,10,size = (2,2))
array1

array([[3, 9],
       [1, 5]])

In [48]:
eigen_values = np.linalg.eigvals(array1)
eigen_values

array([0.83772234, 7.16227766])

In [50]:
eigen_values, eigen_vectors = np.linalg.eig(array1)
eigen_values

array([0.83772234, 7.16227766])

In [51]:
eigen_vectors

array([[-0.97233143, -0.90763558],
       [ 0.23360562, -0.41975903]])