In [20]:
import numpy as np

### Numpy Functions

### Sorting

In [3]:
array = np.sort([3,4,5,6,1,2])
np.sort(array)

array([1, 2, 3, 4, 5, 6])

In [5]:
array = np.sort([3,4,5,6,1,2])
-np.sort(-array)

array([6, 5, 4, 3, 2, 1])

### np.sum

In [8]:
array1 = np.array([3,4,6,1,3,8])
np.sum(array1)

25

### Np.cumsum()

In [14]:
array2 = np.array([0.15,0.20,0.30,0.25,0.1])
array2

array([0.15, 0.2 , 0.3 , 0.25, 0.1 ])

In [15]:
np.sum(array2)

0.9999999999999999

In [16]:
np.cumsum(array2)

array([0.15, 0.35, 0.65, 0.9 , 1.  ])

In [19]:
array2 = np.array([0.15,0.20,0.30,0.25,0.1,0.45,0.60])
print(array2)
np.cumsum(array2)

[0.15 0.2  0.3  0.25 0.1  0.45 0.6 ]


array([0.15, 0.35, 0.65, 0.9 , 1.  , 1.45, 2.05])

In [ ]:
# 100 >> columns
# 0.60, 0.20, 0.10,0.05,0.02

### Delete items from array

In [21]:
array1 = np.array([3,4,5,6,7,2,3])
array1

array([3, 4, 5, 6, 7, 2, 3])

In [23]:
np.delete(array1,1)

array([3, 5, 6, 7, 2, 3])