## Numpy - Trigonometry

In [58]:
import numpy as np

In [ ]:
1. np.sin()
2. np.cos()
3. np.tan()
4. np.deg2rad()
5. np.rad2deg()

In [ ]:
sin >> opp/hyp
cos >> Adj/Hyp
tan >> Opp/Adj

cosec >> 1/sin
sec   >> 1/cos
cot   >> 1/tan

In [3]:
np.pi # 180 degree

3.141592653589793

In [4]:
import math

In [6]:
math.pi

3.141592653589793

### 1. sin

In [7]:
np.sin(np.pi/6) # sin 30

0.49999999999999994

In [9]:
np.sin(np.pi/4) # sin 45

0.7071067811865476

In [11]:
np.sin(np.pi/3)  # sin 60

0.8660254037844386

In [13]:
1.732/2

0.866

In [15]:
np.sin(np.pi/2)  # sin 90

1.0

In [18]:
np.sin(0)  # sin 0

0.0

### 2. cos

In [20]:
np.cos(np.pi/6)# cos30

0.8660254037844387

In [25]:
np.cos(np.pi/4)# cos45

0.7071067811865476

In [26]:
np.cos(np.pi/3)# 

0.5000000000000001

### 3. tan

In [29]:
np.tan(np.pi/6)

0.5773502691896257

In [31]:
np.tan(np.pi/4)

0.9999999999999999

In [33]:
np.tan(np.pi/3)

1.7320508075688767

In [36]:
sec_30 = 1/np.cos(np.pi/6)
sec_30

1.1547005383792515

### degree to radians

In [38]:
np.deg2rad(45)

0.7853981633974483

In [40]:
np.deg2rad(30)

0.5235987755982988

In [43]:
np.sin(np.pi/6) # sin30

0.49999999999999994

In [44]:
np.sin(np.deg2rad(30)) # sin30

0.49999999999999994

In [42]:
np.pi/6

0.5235987755982988

In [49]:
rad_values = np.deg2rad([0,30,45,60,90])
np.sin(rad_values)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [51]:
rad_values = np.deg2rad([0,30,45,60,90])
np.cos(rad_values)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [53]:
rad_values = np.deg2rad([0,30,45,60,90])
np.tan(rad_values)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

### Radians to Degree

In [55]:
rad_values = np.deg2rad([0,30,45,60,90])
rad_values

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [57]:
degree = np.rad2deg(rad_values)
degree

array([ 0., 30., 45., 60., 90.])