# Numpy Functions

In [ ]:
1. np.append()
2. np.concatenate()
3. np.sort()
4. np.add()
5. np.multiply()
6. np.dot()
7. np.floor()
8. np.ceil()
9. np.sqrt()
10. np.cbrt()
11. np.where()

In [ ]:
axis = 0 >> Rows
axis = 1 >> Columns

In [1]:
import numpy as np

In [3]:
array1 = np.random.randint(10,40, size = 10)
array1

array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])

In [5]:
array1 = np.random.randint(10,40, size = (4,3))
array1

array([[23, 12, 21],
       [20, 10, 21],
       [20, 30, 24],
       [22, 12, 24]])

In [8]:
array1 = np.random.randint(10,40, size = (4,3,2))
array1

array([[[24, 29],
        [14, 35],
        [10, 35]],

       [[19, 10],
        [21, 24],
        [21, 15]],

       [[39, 31],
        [10, 25],
        [15, 31]],

       [[24, 24],
        [20, 22],
        [18, 20]]])

In [ ]:
[[39, 31],
[10, 25],
[15, 31]]

In [9]:
array1 = np.array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])
array1

array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])

In [12]:
array1[2] = 300
array1

array([ 36,  35, 300,  18,  31,  21,  27,  24,  27,  17])

In [14]:
array1[2 : 5] = 300
array1

array([ 36,  35, 300, 300, 300,  21,  27,  24,  27,  17])

## 1. append()

In [ ]:
new_array = np.append(array1, value,axis = None)
value >> n-D array

axis = 0 >> Rows
axis = 1 >> Columns

In [17]:
x = np.array(45)
type(x)

numpy.ndarray

In [19]:
array1 = np.array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])

new_array = np.append(array1, 555)
new_array


array([ 36,  35,  30,  18,  31,  21,  27,  24,  27,  17, 555])

In [21]:
array1 = np.array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])

array0 = np.array(444)

new_array = np.append(array1, array0)
new_array


array([ 36,  35,  30,  18,  31,  21,  27,  24,  27,  17, 444])

In [24]:
array1 = np.array([36, 35, 30, 18, 27, 17])

array0 = np.array([10,20,30,40])

new_array = np.append(array1, array0)
new_array


array([36, 35, 30, 18, 27, 17, 10, 20, 30, 40])

In [26]:
array1 = np.array([36, 35, 30, 18, 27, 17])

array0 = np.array([[10,20],[30,40]])

new_array = np.append(array1, array0)
new_array


array([36, 35, 30, 18, 27, 17, 10, 20, 30, 40])

In [27]:
array1 = np.array([[36, 35], [30, 18]])

array2 = np.array([[10,20],[30,40]])


print("Array1 :\n",array1)
print("Array2 :\n",array2)



Array1 :
 [[36 35]
 [30 18]]
Array2 :
 [[10 20]
 [30 40]]


In [ ]:
[[36 35]
 [30 18]
 [10 20]
 [30 40]]

In [ ]:
[[36 35 10 20]
 [30 18 30 40]]

In [29]:
array1 = np.array([[36, 35], [30, 18]])

array2 = np.array([[10,20],[30,40]])


print("Array1 :\n",array1)
print("Array2 :\n",array2)

new_array = np.append(array1,array2) # Return 1 D array
print("New Array \n",new_array)

Array1 :
 [[36 35]
 [30 18]]
Array2 :
 [[10 20]
 [30 40]]
New Array 
 [36 35 30 18 10 20 30 40]


In [ ]:
axis = 0 >> Rows
axis = 1 >> Columns

In [33]:
array1 = np.array([[36, 35], [30, 18]])

array2 = np.array([[10,20],[30,40]])


print("Array1 :\n",array1)
print("Array2 :\n",array2)

new_array = np.append(array1,array2,axis = 0) # Rows
print("New Array \n",new_array)
print(new_array.shape)

Array1 :
 [[36 35]
 [30 18]]
Array2 :
 [[10 20]
 [30 40]]
New Array 
 [[36 35]
 [30 18]
 [10 20]
 [30 40]]
(4, 2)


In [35]:
array1 = np.array([[36, 35], [30, 18]])

array2 = np.array([[10,20],[30,40]])


print("Array1 :\n",array1)
print("Array2 :\n",array2)

new_array = np.append(array1,array2,axis = 1) # Columns
print("New Array \n",new_array)
print(new_array.shape)

Array1 :
 [[36 35]
 [30 18]]
Array2 :
 [[10 20]
 [30 40]]
New Array 
 [[36 35 10 20]
 [30 18 30 40]]
(2, 4)


### 2. concatenate

In [ ]:
np.concatenate([array1, array2, ...,arrayN],axis = 0)

axis = 0 >> Rows
axis = 1 >> COlumns

In [40]:
array1 = np.random.randint(0,10, size= (2,2))
array2 = np.random.randint(10,20, size= (2,2))
array3 = np.random.randint(20,30, size= (2,2))

print("Array1 :\n",array1)
print("Array2 :\n",array2)
print("Array3 :\n",array3)

Array1 :
 [[7 3]
 [3 8]]
Array2 :
 [[14 15]
 [13 11]]
Array3 :
 [[21 22]
 [26 21]]


In [41]:
new_array = np.concatenate([array1, array2])
new_array

array([[ 7,  3],
       [ 3,  8],
       [14, 15],
       [13, 11]])

In [43]:
new_array = np.concatenate([array1, array2,array3])
new_array

array([[ 7,  3],
       [ 3,  8],
       [14, 15],
       [13, 11],
       [21, 22],
       [26, 21]])

In [45]:
new_array = np.concatenate([array1, array2,array3],axis = 0)
new_array

array([[ 7,  3],
       [ 3,  8],
       [14, 15],
       [13, 11],
       [21, 22],
       [26, 21]])

In [47]:
new_array = np.concatenate([array1, array2],axis = 1)
new_array

array([[ 7,  3, 14, 15],
       [ 3,  8, 13, 11]])

In [49]:
new_array = np.concatenate([array1, array3],axis = 1)
new_array

array([[ 7,  3, 21, 22],
       [ 3,  8, 26, 21]])

In [51]:
new_array = np.concatenate([array1, array2, array3],axis = 1)
new_array

array([[ 7,  3, 14, 15, 21, 22],
       [ 3,  8, 13, 11, 26, 21]])

In [54]:
array1 = np.random.randint(0,10, size= (2,2))
array2 = np.random.randint(10,20, size= (4,2))
array3 = np.random.randint(20,30, size= (2,2))

print("Array1 :\n",array1)
print("Array2 :\n",array2)
print("Array3 :\n",array3)

Array1 :
 [[9 8]
 [7 3]]
Array2 :
 [[11 13]
 [15 11]
 [13 17]
 [13 19]]
Array3 :
 [[26 20]
 [20 20]]


In [58]:
new_array = np.concatenate([array1, array2],axis = 0)
new_array

array([[ 9,  8],
       [ 7,  3],
       [11, 13],
       [15, 11],
       [13, 17],
       [13, 19]])

In [59]:
array1 = np.random.randint(0,10, size= (2,2))
array2 = np.random.randint(10,20, size= (2,3))
array3 = np.random.randint(20,30, size= (2,2))

print("Array1 :\n",array1)
print("Array2 :\n",array2)
print("Array3 :\n",array3)

Array1 :
 [[8 4]
 [4 8]]
Array2 :
 [[10 16 10]
 [12 19 13]]
Array3 :
 [[27 24]
 [25 23]]


In [61]:
new_array = np.concatenate([array1, array2],axis = 1)
new_array

array([[ 8,  4, 10, 16, 10],
       [ 4,  8, 12, 19, 13]])

In [62]:
import pandas as pd

In [63]:
pd.DataFrame(new_array)

0  1   2   3   4
0  8  4  10  16  10
1  4  8  12  19  13

### 3. sort

In [ ]:
sorted_array = np.sort(array)

In [64]:
array1 = np.random.randint(20,50,size = 6)
array1

array([34, 45, 30, 38, 23, 42])

In [66]:
sorted_array = np.sort(array1)
sorted_array

array([23, 30, 34, 38, 42, 45])

In [67]:
array1

array([34, 45, 30, 38, 23, 42])

In [70]:
array1 = np.random.randint(20,50,size = (3,4))
array1

array([[46, 49, 26, 34],
       [29, 39, 46, 40],
       [47, 27, 27, 45]])

In [72]:
sorted_array = np.sort(array1)
sorted_array

array([[26, 34, 46, 49],
       [29, 39, 40, 46],
       [27, 27, 45, 47]])

In [75]:
sorted_array = np.sort(array1,axis = None)
sorted_array

array([26, 27, 27, 29, 34, 39, 40, 45, 46, 46, 47, 49])

### 4.Matrix Addition

In [78]:
matrix1 = np.random.randint(10,20,size = (2,2))
matrix2 = np.random.randint(20,40,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

matrix1 :
 [[12 16]
 [12 14]]
matrix2 :
 [[31 25]
 [32 24]]


In [81]:
new_matrix = np.add(matrix1,matrix2)
new_matrix

array([[43, 41],
       [44, 38]])

In [84]:
array1 = np.random.randint(10,20,size = 5)
array2 = np.random.randint(20,40,size = 5)

print("array1 :\n",array1)
print("array2 :\n",array2)

array1 :
 [16 18 16 13 18]
array2 :
 [30 26 23 34 22]


In [88]:
array1 = np.random.randint(10,20,size = 6)
array2 = np.random.randint(20,40,size = 5)

print("array1 :\n",array1)
print("array2 :\n",array2)

np.add(array1,array2)

array1 :
 [10 18 18 12 16 14]
array2 :
 [38 32 33 23 34]


ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [90]:
matrix1 = np.random.randint(10,20,size = (2,2))
matrix2 = np.random.randint(20,40,size = (3,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
np.add(matrix1, matrix2)

matrix1 :
 [[11 16]
 [13 15]]
matrix2 :
 [[38 24]
 [32 39]
 [39 28]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

### 2. Multiplication

In [93]:
matrix1 = np.random.randint(1,10,size = (2,2))
matrix2 = np.random.randint(10,20,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
np.multiply(matrix1, matrix2)

matrix1 :
 [[4 7]
 [5 9]]
matrix2 :
 [[10 19]
 [19 15]]


array([[ 40, 133],
       [ 95, 135]])

In [96]:
array1 = np.random.randint(10,20,size = 5)
array2 = np.random.randint(1,10,size = 5)

print("array1 :\n",array1)
print("array2 :\n",array2)

np.multiply(array1,array2)

array1 :
 [19 14 19 14 15]
array2 :
 [2 8 3 6 8]


array([ 38, 112,  57,  84, 120])

In [98]:
np.add(10,20)

30

In [100]:
np.multiply(10,20)

200

### 3. DotProduct

In [104]:
matrix1 = np.random.randint(1,10,size = (2,2))
matrix2 = np.random.randint(10,20,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)


matrix1 :
 [[3 8]
 [5 7]]
matrix2 :
 [[13 16]
 [16 19]]


In [ ]:
(2 * 2) . (2 * 3)

2 * 3

In [ ]:
3 8     4 6
5 7     5 8 

[3*4 + 8*5      3*6 + 8*8]
[5*4 + 7*5      5*6 + 7*8]


In [107]:
array1 = np.array([[3,8],[5,7]])
array2 = np.array([[4,6],[5,8]])

In [108]:
np.dot(array1,array2)

array([[52, 82],
       [55, 86]])

In [ ]:
2*3  3*2

3 8 7    4 6
5 7 1    5 8
         2 3
    
2 * 2

In [112]:
matrix1 = np.random.randint(1,10,size = (2,2))
matrix2 = np.random.randint(10,20,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

new_array = np.dot(matrix1, matrix2)
new_array

matrix1 :
 [[4 7]
 [8 6]]
matrix2 :
 [[10 11]
 [17 16]]


array([[159, 156],
       [182, 184]])

In [114]:
matrix1 = np.random.randint(1,10,size = (2,3))
matrix2 = np.random.randint(10,20,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

new_array = np.dot(matrix1, matrix2)
new_array

matrix1 :
 [[9 5 9]
 [5 9 6]]
matrix2 :
 [[14 13]
 [19 13]]


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [116]:
matrix1 = np.random.randint(1,10,size = (2,3))
matrix2 = np.random.randint(10,20,size = (3,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

new_array = np.dot(matrix1, matrix2)
new_array

matrix1 :
 [[4 1 6]
 [1 3 2]]
matrix2 :
 [[10 13]
 [17 14]
 [10 14]]


array([[117, 150],
       [ 81,  83]])

In [118]:
matrix1 = np.random.randint(1,10,size = (2,10))
matrix2 = np.random.randint(10,20,size = (10,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

new_array = np.dot(matrix1, matrix2)
new_array

matrix1 :
 [[7 6 2 4 3 1 2 1 9 6]
 [7 6 4 8 9 2 4 6 9 8]]
matrix2 :
 [[10 13]
 [15 16]
 [12 10]
 [10 18]
 [11 14]
 [10 17]
 [16 16]
 [18 18]
 [19 11]
 [13 12]]


array([[566, 559],
       [854, 898]])

In [120]:
matrix1 = np.random.randint(1,10,size = (2,10))
matrix2 = np.random.randint(10,20,size = (10,3))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)

new_array = np.dot(matrix1, matrix2)
new_array

matrix1 :
 [[2 2 3 7 7 6 1 5 1 7]
 [8 1 3 2 6 4 6 5 5 5]]
matrix2 :
 [[12 15 17]
 [14 19 19]
 [11 14 12]
 [11 14 10]
 [15 19 16]
 [13 13 16]
 [15 17 11]
 [13 14 12]
 [19 17 16]
 [15 12 18]]


array([[549, 607, 599],
       [632, 692, 667]])

### Mathematical Operations

In [121]:
array1 = np.array([2,5,7,3,8])


In [123]:
array1 + 10

array([12, 15, 17, 13, 18])

In [125]:
array1 - 1

array([1, 4, 6, 2, 7])

In [127]:
array1 * 10

array([20, 50, 70, 30, 80])

In [129]:
array1 / 10

array([0.2, 0.5, 0.7, 0.3, 0.8])

In [131]:
array1 = np.array([12,5,7,3,8])

array1/3

array([4.        , 1.66666667, 2.33333333, 1.        , 2.66666667])

In [133]:
array1 = np.array([12,5,7,3,8])

array1/4

array([3.  , 1.25, 1.75, 0.75, 2.  ])

In [135]:
array1 = np.array([12,5,7,3,8])

array1//4

array([3, 1, 1, 0, 2], dtype=int32)

In [137]:
array1 = np.array([12,5,7,3,8])

array1 % 4

array([0, 1, 3, 3, 0], dtype=int32)

In [139]:
array1 = np.array([12,5,7,3,8])

array1 ** 2

array([144,  25,  49,   9,  64], dtype=int32)

In [141]:
array1 = np.array([12,5,7,3,8])

array1 ** 3

array([1728,  125,  343,   27,  512], dtype=int32)

### np.floor

In [143]:
np.floor([4.23, 9.12, 1.3456, 10.67, 5.78])

array([ 4.,  9.,  1., 10.,  5.])

In [145]:
np.floor([[4.23, 9.12], [1.3456, 10.67]])

array([[ 4.,  9.],
       [ 1., 10.]])

In [147]:
np.floor(5.7891)

5.0

### np.ceil

In [150]:
np.floor(5.7891) + 1

6.0

In [153]:
array1 = np.array([4.23, 9.12, 1.3456, 10.67, 5.78])
result = np.floor(array1) 
result

array([ 4.,  9.,  1., 10.,  5.])

In [155]:
array1 = np.array([4.23, 9.12, 1.3456, 10.67, 5.78])
result = np.floor(array1)  + 1
result

array([ 5., 10.,  2., 11.,  6.])

In [157]:
array1 = np.array([4.23, 9.12, 1.3456, 10.67, 5.78])
result = np.ceil(array1)
result

array([ 5., 10.,  2., 11.,  6.])

In [160]:
array1 = np.array([4.23, 9.01, 1.3456, 10.67, 5.78])
result = np.ceil(array1)
result

array([ 5., 10.,  2., 11.,  6.])

In [162]:
array1 = np.array([[4.23, 9.01], [1.3456, 10.67]])
result = np.ceil(array1)
result

array([[ 5., 10.],
       [ 2., 11.]])

### np.sqrt

In [163]:
array1 = np.array([64,169,324, 400, 625])

In [165]:
array1 ** 0.5

array([ 8., 13., 18., 20., 25.])

In [167]:
np.sqrt(484)

22.0

In [171]:
sqr_root = np.sqrt(array1)
sqr_root

array([ 8., 13., 18., 20., 25.])

In [173]:
round(4.5677,2)

4.57

In [175]:
np.around(4.5677,2)

4.57

In [180]:
np.around([4.5677,4.67],2).tolist()

[4.57, 4.67]

In [184]:
arr1 = np.random.randint(1,200,size = 5)
print("array1 :",arr1)
np.sqrt(arr1)

array1 : [156 184  95 190 129]


array([12.489996  , 13.56465997,  9.74679434, 13.78404875, 11.35781669])

### np.cbrt

In [186]:
array1 = np.array([64,125, 216, 343,512,729,1000])
np.cbrt(array1)

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [233]:
array1 = np.array([[64,125, 216] ,[343,512,729]])
np.cbrt(array1)

array([[4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
array1 = np.array([64,125, 216, 343,512,729,1000])
np.cbrt(array1)

In [187]:
arr1 = np.random.randint(1,200,size = 5)
np.cbrt(arr1)

array([4.87699896, 5.56129777, 3.27106631, 5.47370367, 5.67741137])

In [190]:
list1 = [3,4,5,3,6,7,8,5,5,1,10]
list1.index(5)

2

In [191]:
index_list = [i for i,val in enumerate(list1) if val == 5]
index_list

[2, 7, 8]

In [193]:
list1 = [3,4,5,3,6,7,8,5,5,1,10]
num = 3
index_list = [i for i,val in enumerate(list1) if val == num]
index_list

[0, 3]

In [195]:
list1 = [3,4,5,3,6,7,8,5,5,1,10]
num = 6
index_list = [i for i,val in enumerate(list1) if val == num]
index_list

[4]

In [197]:
list1 = [3,4,5,3,6,7,8,5,5,1,10]
num = 5
index_list = [i for i,val in enumerate(list1) if val == num]
index_list

[2, 7, 8]

### np.where

In [ ]:
index = np.where(Condition)

In [199]:
list1 = [3,4,5,3,6,7,8,5,5,1,10]
array1 = np.array(list1)
np.where(array1 == 5)

(array([2, 7, 8], dtype=int64),)

In [202]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])

index_list = np.where(array1 > 5)
index_list

(array([ 4,  5,  6, 10], dtype=int64),)

In [207]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])

index_list = np.where(array1 == 5)
type(index_list)

tuple

In [208]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])

index_list = np.where(array1 == 5)
index_list[0]

array([2, 7, 8], dtype=int64)

In [212]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])
array1[2]

5

In [214]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])
array1[[2,4]]

array([5, 6])

In [218]:
array1 = np.array([3,4,5,3,6,7,8,5,5,1,10])

index_list = np.where(array1 == 5)
x = index_list[0]
x

array([2, 7, 8], dtype=int64)

In [219]:
array1[x]

array([5, 5, 5])

In [222]:
array1 = np.array([10,20,30,40,50,10,20,10,30])

index_list = np.where(array1 == 10)
x = index_list[0]
x

array([0, 5, 7], dtype=int64)

In [224]:
array1 = np.array([10,20,30,40,50,10,20,10,30])

index_list = np.where(array1 >= 30)
x = index_list[0]
x

array([2, 3, 4, 8], dtype=int64)

In [226]:
array1 = np.array([10,20,30,40,50,10,20,10,30])

index_list = np.where(array1)
x = index_list[0]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [227]:
array1 = np.array([10,20,30,40,50,10,20,10,30])

index_list = np.where(array1 <= 20 )
x = index_list[0]
x

array([0, 1, 5, 6, 7], dtype=int64)

In [228]:
array1 = np.array([10,20,30,40,50,10,20,10,30])
array1[2]

30

In [232]:
array1 = np.array([10,20,30,40,50,10,20,10,30])
array1[[2,5,3]] # [30,10,40]

array([30, 10, 40])