# Numpy - Revision

In [ ]:
Numpy >> Numerical Python

Indexing and Slicing
Mutable

In [1]:
import numpy as np

## Numpy Functions

In [ ]:
1. np.array([],dtype = float, ndmin = 1)
2. array.ndim
3. array.shape:
    array.shape[0] >> Row Count
    array.shape[1] >> ColumnCount
4. array.tolist() >> n-D array to list
5. array.reshape() >> change dimensions of an array
6. np.nditer()     >> For Loop
7. np.ndenumerate() >> For loop with index
8. array.flatten()  >> Returns copy
9. array.ravel()    >> Returns reference
10. array.copy()    >> Deep Copy
11. np.zeros()
12. np.ones()
13. np.full()
14. np.arange()
15. np.around()
16. np.linspace()
17. np.eye()          >> one or two argument
18. np.identity()     >> Only one argument
19. np.random:
    1. np.random.rand() >> 0 to 1
    2. np.random.randint(start, end, size = (4,5))
    3. np.random.randn() >> Normally distribted Values
    4. np.random.ranf()  >> 0 to 1

20. np.sort() # Ascending
21. -np.sort(-array) # Descending
22. np.where(condition) # Return Index
23. np.delete(array1, index)

### Join Multiple Arrays

In [ ]:
1. np.append(array1, value, axis = None):
    axis = 0 >> Rows
    axis = 1 >> Columns
    
2. np.concatenate([arr1, arr2, ..., arrN],axis = 0)
3. np.concatenate([arr1, arr2, ..., arrN],axis = 1)


## Matrix Operations

In [ ]:
1. np.add()
2. np.multiply()
3. np.dot()


### Math Operations

In [ ]:
1. np.floor():
    np.floor(6.78) >> 6
2. np.ceil():
    np.ceil(6.78)  >> 7
    
3. np.sqrt()
4. np.cbrt()
5. np.add()
6. np.multiply()
7. np.min()
8. np.max()
9. np.sum()
10. np.cumsum()
11. np.pi

### Statistics

In [ ]:
1. np.mean()
2. np.median()
3. np.std()
4. np.var()
5. scipy.stats.mode()[0][0]

### Log

In [ ]:
1. np.log() >> Natural Log
2. np.log2()
3. np.log10()


### Linear Algebra

In [ ]:
1. np.linalg.solve()
2. np.linalg.inv()
3. np.linalg.eigvals()
4. np.linalg.eig() >> Returns Eigen Values and Eigen Vectors
5. poly = np.polynomial.Polynomial():
    poly.roots()

### Trigonometry

In [ ]:
1. np.sin()
2. np.cos()
3. np.tan()
4. np.deg2rad()
5. np.rad2deg()

In [7]:
array1 = np.array([3,4,5,6],dtype = float, ndmin = 2)
array1

array([[3., 4., 5., 6.]])

In [9]:
array1.flatten()

array([3., 4., 5., 6.])

In [10]:
array1.ravel()

array([3., 4., 5., 6.])

In [5]:
array1.ndim

2

In [11]:
array1.shape

(1, 4)

In [15]:
np.floor(4.67)

4.0

In [18]:
array1 = np.array([3,4,5,6])
np.where(array1 == 5)

(array([2], dtype=int64),)

In [23]:
array1 = np.array([3,4,5,6])
array1[1] = 400
array1

array([  3, 400,   5,   6])

In [14]:
np.ceil(4.67)

5.0

In [20]:
np.add(4,5)

9

In [21]:
np.multiply(4,5)

20