## Pandas

In [ ]:
pandas >> Python Data Analysis
Pandas Library is built on topof the Numpy Library


EDA >> Exporatory Data Analysis

matplotlib
seaborn 
plotly

import pandas as pd


### Two Data Structures

In [ ]:
1. DataFrame >> 2-D Data Structure
            Rows and Columns
2. Series: One Dimensional Data Structure

### Use Cases

In [ ]:
1. Read Data From CSV, Excel, JSON
2. Read Data From Database(SQL or NoSQL)
3. Exploratory Data Analysis
4. Data Cleansing:
    Missing Values
    Handle Outliers
    
5. Encoding:
    1. Label Encoding
    2. One Hot Encoding
    
6. Feature Selection
7. Join Multiple Tables
8. Provides Time-Series Functionality

In [1]:
import numpy as np
import pandas as pd

In [3]:
array1 = np.random.randint(10,30,size = (10,5))
array1

array([[24, 26, 14, 10, 24],
       [10, 16, 11, 29, 27],
       [23, 22, 22, 25, 28],
       [12, 10, 25, 22, 16],
       [29, 25, 12, 26, 22],
       [21, 13, 19, 28, 25],
       [24, 21, 17, 28, 28],
       [29, 13, 21, 11, 11],
       [13, 17, 18, 25, 10],
       [29, 17, 12, 22, 26]])

In [7]:
df = pd.DataFrame(array1,columns=['A',"B",'C',"D","E"])
df

A   B   C   D   E
0  24  26  14  10  24
1  10  16  11  29  27
2  23  22  22  25  28
3  12  10  25  22  16
4  29  25  12  26  22
5  21  13  19  28  25
6  24  21  17  28  28
7  29  13  21  11  11
8  13  17  18  25  10
9  29  17  12  22  26

In [9]:
type(df)

pandas.core.frame.DataFrame

In [12]:
s1 = pd.Series([2,3,4,5,4,5,7])
s1

0    2
1    3
2    4
3    5
4    4
5    5
6    7
dtype: int64

In [14]:
type(s1)

pandas.core.series.Series

In [15]:
df

A   B   C   D   E
0  24  26  14  10  24
1  10  16  11  29  27
2  23  22  22  25  28
3  12  10  25  22  16
4  29  25  12  26  22
5  21  13  19  28  25
6  24  21  17  28  28
7  29  13  21  11  11
8  13  17  18  25  10
9  29  17  12  22  26

In [17]:
s2 = df['B']
s2

0    26
1    16
2    22
3    10
4    25
5    13
6    21
7    13
8    17
9    17
Name: B, dtype: int32

### How to Create DataFrame

#### 1. array

In [19]:
array1 = np.random.randint(10,50,size = (6,4))
array1

array([[41, 47, 17, 16],
       [30, 17, 20, 20],
       [31, 29, 35, 10],
       [32, 37, 22, 23],
       [36, 36, 39, 45],
       [24, 47, 46, 26]])

In [22]:
dataframe1 = pd.DataFrame(array1)
print(dataframe1)
dataframe1

    0   1   2   3
0  41  47  17  16
1  30  17  20  20
2  31  29  35  10
3  32  37  22  23
4  36  36  39  45
5  24  47  46  26


0   1   2   3
0  41  47  17  16
1  30  17  20  20
2  31  29  35  10
3  32  37  22  23
4  36  36  39  45
5  24  47  46  26

In [27]:
zeros_array = np.zeros((10,5),dtype = int)
zeros_array
df0 = pd.DataFrame(zeros_array)
df0

0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
5  0  0  0  0  0
6  0  0  0  0  0
7  0  0  0  0  0
8  0  0  0  0  0
9  0  0  0  0  0

In [29]:
zeros_array = np.zeros(10,dtype = int)
zeros_array
# df0 = pd.DataFrame(zeros_array)
# df0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
zeros_array = np.zeros(10,dtype = int)
df0 = pd.DataFrame(zeros_array)
df0

0
0  0
1  0
2  0
3  0
4  0
5  0
6  0
7  0
8  0
9  0

In [34]:
zeros_array = np.zeros(10,dtype = int)
s1 = pd.Series(zeros_array)
s1

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int32

In [37]:
ones_array = np.ones((10,3),dtype = int)
df0 = pd.DataFrame(ones_array)
df0

0  1  2
0  1  1  1
1  1  1  1
2  1  1  1
3  1  1  1
4  1  1  1
5  1  1  1
6  1  1  1
7  1  1  1
8  1  1  1
9  1  1  1

#### 2. Create dataframe using list

In [39]:
list1 = [4,5,6,7,8,9]
df1 = pd.DataFrame(list1)
df1

0
0  4
1  5
2  6
3  7
4  8
5  9

#### 3. Create DataFrame using Tuple

In [41]:
tuple1 = (4,5,6,7,8,9)
df1 = pd.DataFrame(tuple1)
df1

0
0  4
1  5
2  6
3  7
4  8
5  9

#### 4. Create Df using Dictionary

In [ ]:
All arrays must be of the same length

In [45]:
dict1 = {"A" :[3,4,5,6,7],
        "B":(10,20,30,40,50),
        "C": np.array([9,7,5,3,1]),
        "D":np.arange(101,106)}

df = pd.DataFrame(dict1)
df

A   B  C    D
0  3  10  9  101
1  4  20  7  102
2  5  30  5  103
3  6  40  3  104
4  7  50  1  105

In [48]:
dict1 = {"A" :[3,4,5,6,7],
        "B":(10,20,30,40,50),
        "C": np.array([9,7,5,1,30]),
        "D":np.arange(101,106)}

df = pd.DataFrame(dict1)
df

A   B   C    D
0  3  10   9  101
1  4  20   7  102
2  5  30   5  103
3  6  40   1  104
4  7  50  30  105

In [51]:
dict1 = {"A" :[3,4,5,6,7],
        "B":(10,20,30,40,50),
        "C": np.array([9,7,5,1,30]),
        "D":np.arange(101,106),
        "E": pd.Series([40,50,60,20,40])}

df = pd.DataFrame(dict1)
df

A   B   C    D   E
0  3  10   9  101  40
1  4  20   7  102  50
2  5  30   5  103  60
3  6  40   1  104  20
4  7  50  30  105  40

In [58]:
dict1 = {"A" :[3,4,5,6,7],
        "B":(10,20,30,40,50),
        "C": np.array([9,7,5,1,30]),
        "D":np.arange(101,106),
        "E": pd.Series([40,50,60,20,0])}

df = pd.DataFrame(dict1)
df

A   B   C    D   E
0  3  10   9  101  40
1  4  20   7  102  50
2  5  30   5  103  60
3  6  40   1  104  20
4  7  50  30  105   0

In [60]:
df['E']

0    40
1    50
2    60
3    20
4     0
Name: E, dtype: int64

In [63]:
df["F"] = [3,4,5,5,10]
df

A   B   C    D   E   F
0  3  10   9  101  40   3
1  4  20   7  102  50   4
2  5  30   5  103  60   5
3  6  40   1  104  20   5
4  7  50  30  105   0  10

In [65]:
df["G"] = pd.Series([1,2,3,4])
df

A   B   C    D   E   F    G
0  3  10   9  101  40   3  1.0
1  4  20   7  102  50   4  2.0
2  5  30   5  103  60   5  3.0
3  6  40   1  104  20   5  4.0
4  7  50  30  105   0  10  NaN

### 5. Read CSV files

In [66]:
df = pd.read_csv("loan_data.csv")
df

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

### 6. Read Excel

In [67]:
excel_file_path = "Emp_Records.xlsx"
df = pd.read_excel(excel_file_path)
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

### Pandas Functions

In [69]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [71]:
df.columns

Index(['Emp ID', 'First Name', 'Age in Yrs', 'Weight in Kgs', 'Age in Company',
       'Salary', 'City'],
      dtype='object')

In [73]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [77]:
array1 = np.random.randint(1,20,size = (6,4))
array1
df = pd.DataFrame(array1)
df

0   1   2   3
0   8  19   2  14
1   3  19   4  14
2  10   6   1   6
3   1   7  19   1
4   1  14  17   2
5  10   3   6  19

In [82]:
array1 = np.random.randint(1,20,size = (6,4))
df = pd.DataFrame(array1,columns=["A","B","C","D"])
df

A   B   C   D
0   9  15  13   5
1   4  12  11  16
2  16   4   4   3
3   5   1  16  18
4   1  19  17   5
5   9  16   5  17

In [84]:
array1 = np.random.randint(1,20,size = (6,4))
df = pd.DataFrame(array1,columns=list("ABCD"))
df

A   B   C   D
0   2  14   7  17
1  16  19  11  16
2   9  15  10   7
3   1  15   9   7
4  14  18  14  12
5   6   3  13  10

In [83]:
list("ABCD")

['A', 'B', 'C', 'D']

In [86]:
array1 = np.random.randint(1,20,size = (6,4))
df = pd.DataFrame(array1,columns=list("ABCD"),index = list('python'))
df

A   B   C   D
p   5  12   6  16
y   5   1   1   3
t  11   4  13  15
h   8  16  17   4
o   9   1  14   1
n   6   6   2   8

In [88]:
list('python')

['p', 'y', 't', 'h', 'o', 'n']

In [90]:
df

A   B   C   D
p   5  12   6  16
y   5   1   1   3
t  11   4  13  15
h   8  16  17   4
o   9   1  14   1
n   6   6   2   8

In [92]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [94]:
df.index

Index(['p', 'y', 't', 'h', 'o', 'n'], dtype='object')

In [96]:
df.axes

[Index(['p', 'y', 't', 'h', 'o', 'n'], dtype='object'),
 Index(['A', 'B', 'C', 'D'], dtype='object')]

In [99]:
df.columns = list('xyzw')
df

x   y   z   w
p   5  12   6  16
y   5   1   1   3
t  11   4  13  15
h   8  16  17   4
o   9   1  14   1
n   6   6   2   8

In [102]:
df.columns = list('xyzw')
df

x   y   z   w
p   5  12   6  16
y   5   1   1   3
t  11   4  13  15
h   8  16  17   4
o   9   1  14   1
n   6   6   2   8

In [103]:
list1 = [[1,2,3],[10,20,30],[100,200,300]]
df1 = pd.DataFrame(list1)
df1

0    1    2
0    1    2    3
1   10   20   30
2  100  200  300